package com.carrerai.astrology.model;

public enum Nakshatra {

    ASHWINI,
    BHARANI,
    KRITTIKA,
    ROHINI,
    MRIGASHIRA,
    ARDRA,
    PUNARVASU,
    PUSHYA,
    ASHLESHA,
    MAGHA,
    PURVA_PHALGUNI,
    UTTARA_PHALGUNI,
    HASTA,
    CHITRA,
    SWATI,
    VISHAKHA,
    ANURADHA,
    JYESHTHA,
    MULA,
    PURVA_ASHADHA,
    UTTARA_ASHADHA,
    SHRAVANA,
    DHANISHTHA,
    SHATABHISHA,
    PURVA_BHADRAPADA,
    UTTARA_BHADRAPADA,
    REVATI
}