spring.application.name=Astro-Career-AI


# ----------------------------------------
# DATA SOURCE PROPERTIES
# ----------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/astroai
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Specifies the PostgreSQL SQL dialect for Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ----------------------------------------
# JPA / HIBERNATE PROPERTIES
# ----------------------------------------
# Automatically updates the database schema based on your Entity classes
spring.jpa.hibernate.ddl-auto=create

# Shows executed SQL queries in the console (useful for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true